export default {
  '9518-HINOPCAE': { name: 'Historian Interface for OPC Alarm and Events - media only' },
  '9518-HINOPCHDA': { name: 'Historian Interface for OPC HDA - media only' },
  '9518-HINOPCXML': { name: 'Historian Interface for OPC XML plug-in - media only' },
  '9518-HINRELDB': { name: 'Historian Interface for ODBC - media only' },
  '9518-HINDDE': { name: 'Historian Interface for DDE - media only' },
  '9518-HINTCP': { name: 'Historian Interface for TCP Response - media only' },
  '9518-HINTRACE': { name: 'Historian Interface for Trace Route Response - media only' },
  '9518-HINHTML': { name: 'Historian Interface for HTML - media only' },
  '9518-HINXMLFILE': { name: 'Historian Interface for File Reader XML plug-in - media only' },
  '9518-HINBATFILE': { name: 'Historian Interface for Batch Files - media only' },
  '9518-HINUNIFILE': { name: 'Historian Interface for Universal File Loader - media only' },
  '9518-HINWINEVT': { name: 'Historian Interface for MS Windows Event File - media only' },
  '9518-HINDNP3': { name: 'Historian Interface for DNP 3.0 - media only' },
  '9518-HINFFT': { name: 'Historian Interface for Fourier Transformations - media only' },
  '9518-HINPERFMON': { name: 'Historian Interface for Historian Performance Monitor - media only' },
  '9518-HINEPLC': { name: 'Historian Interface for Modbus Ethernet - media only' },
  '9518-HINMPLC': { name: 'Historian Interface for Modbus/Modbus Plus PLC - media only' },
  '9518-HINABBIMS': { name: 'Historian Interface for ABB IMS Advant - media only' },
  '9518-HINABBPDL': { name: 'Historian Interface for ABB IMS Advant PDL - media only' },
  '9518-HINABBPBS': { name: 'Historian Interface for ABB Procontrol P for PBS - media only' },
  '9518-HINCITECH': { name: 'Historian Interface for Citech - media only' },
  '9518-HINFOXBORO': { name: 'Historian Interface for Foxboro AW70 Series - media only' },
  '9518-HINGECIMPL': { name: 'Historian Interface for GE Cimplicity - media only' },
  '9518-HINGEPAC4K': { name: 'Historian Interface for GE PAC 4010/4020 - media only' },
  '9518-HINHONPHD': { name: 'Historian Interface for Honeywell PHD - media only' },
  '9518-HINHONSC3K': { name: 'Historian Interface for Honeywell Scan3000 - media only' },
  '9518-HINASPEN': { name: 'Historian Interface for AspenTech CIM-IO Client - media only' },
  '9518-HINIFIX': { name: 'Historian Interface for Intellution FIX (FIX32/iFIX) - media only' },
  '9518-HININTOUCH': { name: 'Historian Interface for Wonderware inTouch - media only' }
}
