export default {
  '9528-VPSERVERENE': { name: 'ESD - PlantPAx System - Software - FactoryTalk VantagePoint EMI Server' },
  '9528-VPSERVERENM': { name: 'MEDIA - PlantPAx System - Software - FactoryTalk VantagePoint EMI Server' },
  '9528-VPCL01ENE': { name: 'ESD - PlantPAx System - Software - FactoryTalk VantagePoint 1 Concurrent User' },
  '9528-VPCL01ENM': { name: 'MEDIA - PlantPAx System - Software - FactoryTalk VantagePoint 1 Concurrent User' },
  '9528-VPCL03ENE': { name: 'ESD - PlantPAx System - Software - FactoryTalk VantagePoint 3 Concurrent Users' },
  '9528-VPCL03ENM': { name: 'MEDIA - PlantPAx System - Software - FactoryTalk VantagePoint 3 Concurrent Users' },
  '9528-VPCL05ENE': { name: 'ESD - PlantPAx System - Software - FactoryTalk VantagePoint 5 Concurrent Users' },
  '9528-VPCL05ENM': { name: 'MEDIA - PlantPAx System - Software - FactoryTalk VantagePoint 5 Concurrent Users' },
  '9528-VPCPPENE': { name: 'ESD - PlantPAx System - Software - FactoryTalk VantagePoint Concurrent User CPU License (Per CPU)' },
  '9528-VPCPPENM': { name: 'MEDIA - PlantPAx System - Software - FactoryTalk VantagePoint Concurrent User CPU License (Per CPU)' },
  '9528-VPHSCENE': { name: 'ESD - PlantPAx System - Software - FactoryTalk VantagePoint 3rd-Party Historican Connector (Licensed per connector instance)' },
  '9528-VPHSCENM': { name: 'MEDIA - PlantPAx System - Software - FactoryTalk VantagePoint 3rd-Party Historican Connector (Licensed per connector instance)' },
  '9528-VPNL01ENE': { name: 'ESD - PlantPAx System - Software - FactoryTalk VantagePoint 1 Named User' },
  '9528-VPNL01ENM': { name: 'MEDIA - PlantPAx System - Software - FactoryTalk VantagePoint 1 Named User' },
  '9528-VPNL03ENE': { name: 'ESD - PlantPAx System - Software - FactoryTalk VantagePoint 3 Named User' },
  '9528-VPNL03ENM': { name: 'MEDIA - PlantPAx System - Software - FactoryTalk VantagePoint 3 Named User' },
  '9528-VPNL05ENE': { name: 'ESD - PlantPAx System - Software - FactoryTalk VantagePoint 5 Named User' },
  '9528-VPNL05ENM': { name: 'MEDIA - PlantPAx System - Software - FactoryTalk VantagePoint 5 Named User' },
  '9528-VPNL010ENE': { name: 'ESD - PlantPAx System - Software - FactoryTalk VantagePoint 10 Named User' },
  '9528-VPNL010ENM': { name: 'MEDIA - PlantPAx System - Software - FactoryTalk VantagePoint 10 Named User' },
}