export default {
  '9515-ASTSRVRENE': { name: 'FactoryTalk AssetCentre Server' },
  '9515-ASTCAP0005E': { name: 'FactoryTalk AssetCentre 5 additional assets' },
  '9515-ASTCAP0025E': { name: 'FactoryTalk AssetCentre 25 additional assets' },
  '9515-ASTCAP0100E': { name: 'FactoryTalk AssetCentre 100 additional assets' },
  '9515-ASTCAP0500E': { name: 'FactoryTalk AssetCentre 500 additional assets' },
  '9515-ASTCAP1000E': { name: 'FactoryTalk AssetCentre 1000 additional assets' },
  '9515-ASTCAP5000E': { name: 'FactoryTalk AssetCentre 5000 additional assets' },
  '9515-ASTCAPSITE': { name: 'FactoryTalk AssetCentre Asset Capacity Site License' },
  '9515-ASTDRROKENE': { name: 'FactoryTalk  AssetCentre Disaster Recovery for Rockwell Automation' },
  '9515-ASTDRFNCENE': { name: 'FactoryTalk  AssetCentre Disaster Recovery for Fanuc Robot' },
  '9515-ASTDRMTNENE': { name: 'FactoryTalk  AssetCentre Disaster Recovery for Motoman Robot' },
  '9515-ASTDRABBENE': { name: 'FactoryTalk  AssetCentre Disaster Recovery for ABB Robot' },
  '9515-ASTDRRCENE': { name: 'FactoryTalk  AssetCentre Disaster Recovery for Remote Computers' },
  '9515-ASTDRSMNS5E': { name: 'FactoryTalk  AssetCentre Disaster Recovery for Siemens S5' },
  '9515-ASTDRSMNS7E': { name: 'FactoryTalk  AssetCentre Disaster Recovery for Siemens S7' },
  '9515-ASTDRFTPENE': { name: 'FactoryTalk  AssetCentre Disaster Recovery for Generic FTP' },
  '9515-ASTDRCDPENE': { name: 'FactoryTalk  AssetCentre Disaster Recovery Custom Device Plug-in' },
  '9515-ASTAGCAP4': { name: 'FactoryTalk  AssetCentre 4 Additional Agent Groups' },
  '9515-ASTPRDCFENE': { name: 'FactoryTalk  AssetCentre Process Device Configuration' },
  '9515-ASTSRVSTENE': { name: 'FactoryTalk  AssetCentre System Starter' },
  '9515-ASTPRDSTENE': { name: 'FactoryTalk  AssetCentre Process Starter' },
  '9515-ASTCLMANENE': { name: 'FactoryTalk  AssetCentre Calibration Management' },
  '9515-ASTCLWRKENE': { name: 'FactoryTalk  AssetCentre Calibration Management Remote Workstation' },
  '9515-ASTCLFLKENE': { name: 'FactoryTalk  AssetCentre Calibration Management Fluke Documenting Calibrator Interface' }
}